'use strict';

// Action IDs -----------------------------------------------------------------
var actions = [
    'SERVER_MESSAGE_HELLO',
    'CLIENT_MESSAGE_LOGIN',
    'SERVER_RESPOND_LOGIN',

    'SERVER_MESSAGE_ROOM_LIST',

    'CLIENT_MESSAGE_ROOM_CREATE',
    'SERVER_RESPOND_ROOM_CREATED',

    'CLIENT_MESSAGE_ROOM_JOIN',
    'SERVER_RESPOND_ROOM_JOINED',
    'CLIENT_MESSAGE_ROOM_LEAVE',
    'SERVER_RESPOND_ROOM_LEFT',
    'SERVER_MESSAGE_ROOM_PLAYER_JOINED',
    'SERVER_MESSAGE_ROOM_PLAYER_LEFT',

    'SERVER_MESSAGE_ROOM_PLAYER_LIST',
    'SERVER_MESSAGE_ROOM_JOINED',

    'CLIENT_MESSAGE_ROOM_SET_PARAM',
    'SERVER_RESPOND_ROOM_PARAM_SET',
    'SERVER_MESSAGE_ROOM_PARAM_SET',

    'CLIENT_MESSAGE_ROOM_SET_PASSWORD',
    'SERVER_RESPOND_ROOM_PASSWORD_SET',

    'SERVER_MESSAGE_ROOM_COUNTDOWN_STARTED',
    'SERVER_MESSAGE_ROOM_COUNTDOWN_UPDATED',
    'SERVER_MESSAGE_ROOM_COUNTDOWN_ENDED',
    'SERVER_MESSAGE_ROOM_COUNTDOWN_CANCELED',

    'CLIENT_MESSAGE_ROOM_CANCEL_COUNTDOWN',
    'SERVER_RESPOND_ROOM_COUNTDOWN_CANCELED',

    'SERVER_MESSAGE_ROOM_LOAD',
    'CLIENT_RESPOND_ROOM_LOADED',
    'CLIENT_MESSAGE_ROOM_START',
    'SERVER_MESSAGE_ROOM_STARTED',
    'SERVER_RESPOND_ROOM_START',

    'CLIENT_MESSAGE_ROOM_SET_OWNER',
    'SERVER_RESPOND_ROOM_OWNER_SET',
    'SERVER_MESSAGE_ROOM_SET_OWNER',

    'SERVER_MESSAGE_TICK_UPDATE',
    'CLIENT_RESPOND_TICK_CONFIRM',

    'ERROR',
    'ERROR_INVALID_PARAMETER',
    'ERROR_PROTOCOL_MISMATCH',
    'ERROR_INVALID_MESSAGE',
    'ERROR_UNKNOWN_ACTION',

    'ERROR_ROOM_STARTED',
    'ERROR_ROOM_GAME_IDENT',
    'ERROR_ROOM_GAME_VERSION',
    'ERROR_ROOM_FULL',
    'ERROR_ROOM_NOT_READY',
    'ERROR_ROOM_NOT_OWNER',
    'ERROR_ROOM_NOT_FOUND',
    'ERROR_ROOM_ALREADY_EXIST',
    'ERROR_ROOM_INVALID_PASSWORD',
    'ERROR_SERVER_NAME_IN_USE',
    'ERROR_ROOM_NOT_COUNTING_DOWN',
    'ERROR_SERVER_MAX_PLAYERS'

];

// Create Mappings ------------------------------------------------------------
var reverseMap = {};
actions.forEach(function(action, index) {
    reverseMap[index] = action;
    exports[action] = index;
});

exports.getNameFromId = function(id) {
    return reverseMap[id];
};

